[package]
name = "day-24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
divan = "0.1.17"

[[bench]]
name = "day-24-bench"
path = "benches/benchmarks.rs"
harness = false